id: com.qq.weixin
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
command: wechat
separate-locales: false

finish-args:
  - --share=ipc
  - --share=network
  - --socket=x11
  - --socket=pulseaudio
  - --device=all
  - --talk-name=org.a11y.Bus
  # File Manager
  - --talk-name=org.freedesktop.FileManager1
  # System tray icon
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.kde.StatusNotifierWatcher
  # Uses legacy StatusNotifier implementation
  - --own-name=org.kde.*
  # Files
  - --filesystem=xdg-download:ro
  - --persist=.xwechat
  - --persist=xwechat_files
  # Hidpi scale
  - --env=QT_AUTO_SCREEN_SCALE_FACTOR=1
  # Only supports xcb
  - --env=QT_QPA_PLATFORM=xcb
  # Fcitx5 Input Methoe
  - --env=QT_IM_MODULE=fcitx
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc

modules:
  - name: kerberos
    subdir: src
    config-opts:
      - --disable-static
      - --disable-rpath
    sources:
      - type: archive
        url: https://kerberos.org/dist/krb5/1.22/krb5-1.22.1.tar.gz
        sha256: 1a8832b8cad923ebbf1394f67e2efcf41e3a49f460285a66e35adec8fa0053af
        x-checker-data:
          type: anitya
          project-id: 13287
          stable-only: true
          url-template: https://kerberos.org/dist/krb5/${version0}.${version1}/krb5-${version0}.${version1}.${version2}.tar.gz

  - name: patchelf
    sources:
      - type: archive
        url: https://github.com/NixOS/patchelf/releases/download/0.18.0/patchelf-0.18.0.tar.gz
        sha256: 64de10e4c6b8b8379db7e87f58030f336ea747c0515f381132e810dbf84a86e7
        x-checker-data:
          type: anitya
          project-id: 2598
          stable-only: true
          url-template: https://github.com/NixOS/patchelf/releases/download/$version/patchelf-$version.tar.gz
    cleanup:
      - /share

  - name: wechat
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - install -Dvm755 apply_extra -t ${FLATPAK_DEST}/bin
      - install -Dvm755 wechat -t ${FLATPAK_DEST}/bin
      - install -Dvm755 dde-file-manager -t ${FLATPAK_DEST}/bin
      - install -Dvm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
      - install -Dvm644 ${FLATPAK_ID}.png -t ${FLATPAK_DEST}/share/icons/hicolor/256x256/apps
      - install -Dvm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications
    sources:
      - type: script
        commands:
          - bsdtar -O -xvf wechat.deb data.* | bsdtar --no-same-owner -xvf -
          - mv -v opt/wechat wechat
          - rm -rv wechat.deb usr opt
          - patchelf --clear-execstack wechat/libandromeda.so wechat/libowl.so wechat/libvoipCodec.so
        dest-filename: apply_extra

      - type: script
        commands:
          - exec /app/extra/wechat/wechat
        dest-filename: wechat

      - type: file
        path: dde-file-manager

      - type: file
        path: com.qq.weixin.metainfo.xml

      - type: file
        path: com.qq.weixin.png

      - type: file
        path: com.qq.weixin.desktop

      - type: extra-data
        filename: wechat.deb
        only-arches: [x86_64]
        url: https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_x86_64.deb
        sha256: 869a8156318e2275237c280a637cb86ce7bd427ddb95864699b21c7f3ce64a29
        size: 221182460

      - type: extra-data
        filename: wechat.deb
        only-arches: [aarch64]
        url: https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_arm64.deb
        sha256: 32f4116a6964f570ba2441046a9094fb5b726398bead4e91fedee52a5215b351
        size: 196015840
