app-id: com.qq.qqmusic
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: '25.08'
command: qqmusic

finish-args:
  - --socket=wayland
  - --socket=pulseaudio
  - --device=dri
  - --share=network
  - --talk-name=org.kde.StatusNotifierWatcher
  - --own-name=org.mpris.MediaPlayer2.chromium.*
  - --system-talk-name=org.freedesktop.login1
  - --system-talk-name=org.chromium.bluetooth.Manager
  # required to fix cursor scaling on wayland
  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons

add-extensions:
  org.freedesktop.Platform.electron:
    version: '25.08'
    directory: electron

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc

modules:
  - name: qqmusic
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - mkdir -pv ${FLATPAK_DEST}/qqmusic
      - mkdir -pv ${FLATPAK_DEST}/electron
      - install -Dvm644 app.asar -t ${FLATPAK_DEST}/qqmusic
      - install -Dvm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
      - install -Dvm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications
      - install -Dvm644 ${FLATPAK_ID}.png -t ${FLATPAK_DEST}/share/icons/hicolor/256x256/apps/
      - install -Dvm755 qqmusic.sh ${FLATPAK_DEST}/bin/qqmusic
    sources:
      - type: file
        path: com.qq.qqmusic.metainfo.xml
      - type: file
        path: com.qq.qqmusic.desktop
      - type: file
        path: com.qq.qqmusic.png
      - type: file
        dest-filename: app.asar
        url: https://q.askk.cc/qqmusic_1.1.8-1.asar
        sha256: 3d675f5dff41b3371d88d5ddbae39d0ad599b04d75a3d7eb50ab0f9b4244f0cd
      - type: script
        dest-filename: qqmusic.sh
        commands:
          - export TMPDIR=${XDG_RUNTIME_DIR}/app/${FLATPAK_ID}
          - exec zypak-wrapper "/app/electron/electron" "/app/qqmusic/app.asar" "--enable-features=UseOzonePlatform" "--ozone-platform=wayland"
            "--enable-wayland-ime" "--wayland-text-input-version=3" "$@"
