app-id: com.cloudchewie.cloudotp
runtime: org.gnome.Platform
runtime-version: '46'
sdk: org.gnome.Sdk
command: CloudOTP
finish-args:
  - --share=ipc
  - --socket=wayland
  - --socket=fallback-x11
  - --socket=pulseaudio
  - --share=network
  - --device=dri
  - --talk-name=org.kde.StatusNotifierWatcher
  - --talk-name=org.freedesktop.Notifications
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc

modules:
  - shared-modules/libsecret/libsecret.json

  - name: keybinder3
    buildsystem: autotools
    post-install:
      - install -Dm644 COPYING /app/share/licenses/keybinder-3/COPYING
    sources:
      - type: archive
        url: https://github.com/kupferlauncher/keybinder/releases/download/keybinder-3.0-v0.3.2/keybinder-3.0-0.3.2.tar.gz
        sha256: e6e3de4e1f3b201814a956ab8f16dfc8a262db1937ff1eee4d855365398c6020

  - name: libnotify
    buildsystem: meson
    config-opts:
      - -Dman=false
      - -Dtests=false
      - -Dgtk_doc=false
      - -Ddocbook_docs=disabled
    sources:
      - type: archive
        url: https://download.gnome.org/sources/libnotify/0.8/libnotify-0.8.3.tar.xz
        sha256: ee8f3ef946156ad3406fdf45feedbdcd932dbd211ab4f16f75eba4f36fb2f6c0
        x-checker-data:
          project-id: 13149
          type: anitya
          url-template: https://download.gnome.org/sources/libnotify/$major.$minor/libnotify-$version.tar.xz

  - name: libayatana-appindicator
    buildsystem: cmake-ninja
    config-opts:
      - -DENABLE_BINDINGS_MONO=NO
      - -DENABLE_BINDINGS_VALA=NO
      - -DENABLE_GTKDOC=NO
    sources:
      - type: git
        url: https://github.com/AyatanaIndicators/libayatana-appindicator.git
        tag: 0.5.93
        commit: 238c8b02718fa5b4af95ede72beeed762094f4cc
        x-checker-data:
          type: anitya
          project-id: 18446
          tag-template: $version

    modules:
      - shared-modules/intltool/intltool-0.51.json

      - name: ayatana-ido
        buildsystem: cmake-ninja
        sources:
          - type: git
            url: https://github.com/AyatanaIndicators/ayatana-ido.git
            tag: 0.10.4
            commit: f968079b09e2310fefc3fc307359025f1c74b3eb
            x-checker-data:
              type: anitya
              project-id: 18445
              tag-template: $version

      - name: libayatana-indicator
        buildsystem: cmake-ninja
        sources:
          - type: git
            url: https://github.com/AyatanaIndicators/libayatana-indicator.git
            tag: 0.9.4
            commit: 611bb384b73fa6311777ba4c41381a06f5b99dad
            x-checker-data:
              type: anitya
              project-id: 18447
              tag-template: $version

      - name: libdbusmenu-gtk3
        buildsystem: autotools
        build-options:
          cflags: -Wno-error
        config-opts:
          - --with-gtk=3
          - --disable-dumper
          - --disable-static
          - --enable-tests
          - --disable-gtk-doc
          - --enable-introspection=no
          - --disable-vala
        cleanup:
          - /share/gtk-doc
          - /share/libdbusmenu
        sources:
          - type: archive
            url: https://launchpad.net/libdbusmenu/16.04/16.04.0/+download/libdbusmenu-16.04.0.tar.gz
            sha256: b9cc4a2acd74509435892823607d966d424bd9ad5d0b00938f27240a1bfa878a

  - name: sqlcipher
    config-opts:
      - --enable-tempstore=yes
      - FLAGS=-DSQLITE_HAS_CODEC
      - LDFLAGS=-lcrypto -lm
    cleanup:
      - /bin
      - /man
    sources:
      - type: git
        url: https://github.com/sqlcipher/sqlcipher.git
        tag: v4.6.1
        x-checker-data:
          type: anitya
          project-id: 11213
          stable-only: true
          tag-template: v$version
        commit: c5bd336ece77922433aaf6d6fe8cf203b0c299d5
    modules:
      - name: tcl
        subdir: unix
        config-opts:
          - --enable-shared=no
        build-options:
          no-debuginfo: true
        cleanup:
          - /bin
          - /man
        sources:
          - type: archive
            url: https://downloads.sourceforge.net/project/tcl/Tcl/8.6.14/tcl8.6.14-src.tar.gz
            sha256: 5880225babf7954c58d4fb0f5cf6279104ce1cd6aa9b71e9a6322540e1c4de66
            x-checker-data:
              type: anitya
              project-id: 4941
              stable-only: true
              url-template: https://downloads.sourceforge.net/project/tcl/Tcl/$version/tcl$version-src.tar.gz

  - name: cloudotp
    buildsystem: simple
    build-commands:
      - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
      - mv opt/CloudOTP /app/
      - cp -a usr/share /app/
      - chmod +x /app/CloudOTP/CloudOTP
      - install -Dm755 CloudOTP.sh /app/bin/CloudOTP
      - install -Dm644 com.cloudchewie.cloudotp.metainfo.xml -t /app/share/metainfo
    sources:
      - type: file
        only-arches: [x86_64]
        url: https://github.com/Robert-Stackflow/CloudOTP/releases/download/V2.4.4/CloudOTP-2.4.4-linux-amd64.deb
        sha256: 23794dc7f479b0a6c16c0f1d271b7f8672c3e654f8974f89d6c044d0a825d1b7
        x-checker-data:
          type: json
          url: https://api.github.com/repos/Robert-Stackflow/CloudOTP/releases/latest
          version-query: .tag_name | sub("^V"; "")
          url-query: >-
            .assets[] | select(.name=="CloudOTP-" + $version + "-linux-amd64.deb")
            |
            .browser_download_url
      - type: file
        path: com.cloudchewie.cloudotp.metainfo.xml
      - type: script
        commands:
          - export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"
          - /app/CloudOTP/CloudOTP
        dest-filename: CloudOTP.sh
