app-id: io.github.iota9star.mikan
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
command: mikan
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --share=network
  - --device=dri
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc
modules:
  - name: mikan
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - unzip mikan.zip
      - mkdir mikan-package
      - mv {data,lib,mikan} mikan-package/
      - mv mikan-package /app/mikan
      - install -Dm755 mikan.sh /app/bin/mikan
      - install -Dm644 io.github.iota9star.mikan.metainfo.xml -t /app/share/metainfo/
      - install -Dm644 io.github.iota9star.mikan.png -t /app/share/icons/hicolor/256x256/apps/
      - install -Dm644 io.github.iota9star.mikan.desktop -t /app/share/applications/
    sources:
      - type: file
        url: https://github.com/iota9star/mikan_flutter/releases/download/v1.2.9/linux-release.zip
        dest-filename: mikan.zip
        only-arches: [x86_64]
        sha256: 89148ce4ccf9462adef137267b1fe6aebd03dcc68161dcf1ed6953d0dcd8621b
        x-checker-data:
          type: json
          url: https://api.github.com/repos/iota9star/mikan_flutter/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: >-
            .assets[] | select(.name=="linux-release.zip")
            |
            .browser_download_url

      - type: file
        path: io.github.iota9star.mikan.metainfo.xml

      - type: file
        path: io.github.iota9star.mikan.desktop

      - type: file
        path: io.github.iota9star.mikan.png

      - type: script
        commands:
          - export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"
          - /app/mikan/mikan "$@"
        dest-filename: mikan.sh
