app-id: co.anysphere.cursor
runtime: org.freedesktop.Sdk
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.golang
base: org.electronjs.Electron2.BaseApp
base-version: '24.08'
command: cursor
finish-args:
  - --share=network
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  - --socket=ssh-auth
  - --device=all
  - --allow=devel
  - --filesystem=host
  - --env=NPM_CONFIG_GLOBALCONFIG=/app/etc/npmrc
  - --env=LD_LIBRARY_PATH=/app/lib
  # required to fix cursor scaling on wayland
  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
  - --system-talk-name=org.freedesktop.login1
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.freedesktop.secrets
  - --talk-name=org.kde.kwalletd5
  - --talk-name=org.freedesktop.Flatpak
  - --filesystem=xdg-run/gnupg:ro
  - --filesystem=xdg-config/kdeglobals:ro
  - --talk-name=com.canonical.AppMenu.Registrar

add-extensions:
  com.visualstudio.code.tool:
    directory: tools
    subdirectories: true
    versions: stable;24.08
    add-ld-path: lib
    no-autodownload: true

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc

modules:
  - shared-modules/libusb/libusb.json

  # Provide libsecret without gcrypt, forcing it to use the D-Bus backend
  # https://github.com/flathub/org.signal.Signal/pull/756/commits/2caf105b18f906e7707f67b3cf7384a21f461564
  - name: libsecret
    buildsystem: meson
    config-opts:
      - -Dmanpage=false
      - -Dcrypto=disabled
      - -Dvapi=false
      - -Dgtk_doc=false
      - -Dintrospection=false
      - -Dbash_completion=disabled
    cleanup:
      - /bin
      - /include
      - /lib/pkgconfig
      - /share/man
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/libsecret.git
        tag: 0.21.6
        commit: e59012225c2857d53738574423416b541f11a131
        x-checker-data:
          type: git
          tag-pattern: ^([\d.]+)$

  - name: host-spawn
    buildsystem: simple
    build-options:
      build-args:
        - --share=network
      append-path: /usr/lib/sdk/golang/bin
    build-commands:
      - CGO_ENABLED=0 go build -ldflags "-X main.Version=$(grep -m1 -oP '^\s*##\s*\K\d+\.\d+\.\d+' CHANGELOG.md)" -o "${FLATPAK_DEST}/bin/host-spawn"
    sources:
      - type: git
        url: https://github.com/1player/host-spawn
        tag: v1.6.1
        commit: db1173ae2ef04beca8961a35c225117498263e23
        x-checker-data:
          type: git
          tag-pattern: ^v([\d.]+)$

  - name: unappimage
    buildsystem: simple
    build-commands:
      - make -C squashfs-tools install INSTALL_DIR=${FLATPAK_DEST}/bin
    sources:
      - type: git
        url: https://github.com/refi64/unappimage
        commit: d7f86f2a0d7ec3a69211125207d5f127386b849a

  - name: cursor
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - install -Dm755 cursor -t ${FLATPAK_DEST}/bin/
      - install -Dm644 ${FLATPAK_ID}.png -t ${FLATPAK_DEST}/share/icons/hicolor/512x512/apps/
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo/
      - install -Dm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications/
      - install -Dm644 npmrc -t ${FLATPAK_DEST}/etc/
      - install -Dm644 flatpak-warning.txt -t ${FLATPAK_DEST}/share/cursor
      - install -Dm755 apply_extra -t ${FLATPAK_DEST}/bin/
      - mkdir ${FLATPAK_DEST}/tools
    sources:
      - type: script
        dest-filename: apply_extra
        commands:
          - chmod +x cursor.AppImage
          - unappimage cursor.AppImage >/dev/null
          - mv squashfs-root cursor
          - rm -rf cursor.AppImage cursor/{usr,AppRun,cursor.desktop,cursor.png,.DirIcon}
          # # fix double-title-bars bugs
          # - sed -i 's/,minHeight/,frame:false,minHeight/g' "cursor/resources/app/out/vs/code/electron-main/main.js"
      - type: file
        path: com.cursor.cursor.metainfo.xml
      - type: file
        path: com.cursor.cursor.desktop
      - type: file
        path: com.cursor.cursor.png
      - type: file
        path: cursor
      - type: file
        path: npmrc
      - type: file
        path: flatpak-warning.txt
      - type: extra-data
        filename: cursor.AppImage
        only-arches: [x86_64]
        url: https://anysphere-binaries.s3.us-east-1.amazonaws.com/production/client/linux/x64/appimage/Cursor-0.46.10-7b3e0d45d4f952938dbd8e1e29c1b17003198481.deb.glibc2.25-x86_64.AppImage
        sha256: 0c171d9f9e24a9e8675877e3fa75d32323ddc71d1364b63f343c7f55851bc787
        size: 186135744
        # x-checker-data:
        #   type: json
        #   url: https://api2.cursor.sh/updates/api/update/linux-x64/cursor/0.0.0/
        #   version-query: .version
        #   url-query: .url
      - type: extra-data
        filename: cursor.AppImage
        only-arches: [aarch64]
        url: https://download.todesktop.com/230313mzl4w4u92/cursor-0.45.14-build-250219jnihavxsz-arm64.AppImage
        sha256: f0e5253ee3cd82a6c67b6c7b806fa6de7deee940ef82755e9248c9d3ca55391b
        size: 154439047
        # x-checker-data:
        #   type: json
        #   url: https://api2.cursor.sh/updates/api/update/linux-arm/cursor/0.0.0/
        #   version-query: .version
        #   url-query: .url
