app-id: com.cursor.cursor
runtime: org.freedesktop.Sdk
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: '24.08'
command: cursor
separate-locales: false
finish-args:
  - --share=network
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  - --socket=ssh-auth
  - --device=all
  - --allow=devel
  - --filesystem=host
  - --env=NPM_CONFIG_GLOBALCONFIG=/app/etc/npmrc
  - --env=LD_LIBRARY_PATH=/app/lib
  # required to fix cursor scaling on wayland
  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
  - --system-talk-name=org.freedesktop.login1
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.freedesktop.secrets
  - --talk-name=org.kde.kwalletd5
  - --talk-name=org.freedesktop.Flatpak
  - --filesystem=xdg-run/gnupg:ro
  - --filesystem=xdg-config/kdeglobals:ro
  - --talk-name=com.canonical.AppMenu.Registrar

add-extensions:
  com.visualstudio.code.tool:
    directory: tools
    subdirectories: true
    versions: stable;24.08
    add-ld-path: lib
    no-autodownload: true

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc

modules:
  - shared-modules/libusb/libusb.json

  # Provide libsecret without gcrypt, forcing it to use the D-Bus backend
  # https://github.com/flathub/org.signal.Signal/pull/756/commits/2caf105b18f906e7707f67b3cf7384a21f461564
  - name: libsecret
    buildsystem: meson
    config-opts:
      - -Dmanpage=false
      - -Dcrypto=disabled
      - -Dvapi=false
      - -Dgtk_doc=false
      - -Dintrospection=false
      - -Dbash_completion=disabled
    cleanup:
      - /bin
      - /include
      - /lib/pkgconfig
      - /share/man
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/libsecret.git
        tag: 0.21.6
        commit: e59012225c2857d53738574423416b541f11a131
        x-checker-data:
          type: git
          tag-pattern: ^([\d.]+)$

  - name: unappimage
    buildsystem: simple
    build-commands:
      - make -C squashfs-tools install INSTALL_DIR=${FLATPAK_DEST}/bin
    sources:
      - type: git
        url: https://github.com/refi64/unappimage
        commit: d7f86f2a0d7ec3a69211125207d5f127386b849a

  - name: cursor
    buildsystem: simple
    build-commands:
      - install -Dm755 cursor -t ${FLATPAK_DEST}/bin/
      - install -Dm644 ${FLATPAK_ID}.png -t ${FLATPAK_DEST}/share/icons/hicolor/512x512/apps/
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo/
      - install -Dm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications/
      - install -Dm644 npmrc -t ${FLATPAK_DEST}/etc/
      - install -Dm644 flatpak-warning.txt -t ${FLATPAK_DEST}/share/cursor
      - install -Dm755 apply_extra -t ${FLATPAK_DEST}/bin/
      - mkdir ${FLATPAK_DEST}/tools
    sources:
      - type: script
        dest-filename: apply_extra
        commands:
          - chmod +x cursor.AppImage
          - unappimage cursor.AppImage >/dev/null
          - mv squashfs-root cursor
          - rm -rf cursor.AppImage cursor/{usr,AppRun,cursor.desktop,cursor.png,.DirIcon}
          # # fix double-title-bars bugs
          # - sed -i 's/,minHeight/,frame:false,minHeight/g' "cursor/resources/app/out/vs/code/electron-main/main.js"
      - type: file
        path: com.cursor.cursor.metainfo.xml
      - type: file
        path: com.cursor.cursor.desktop
      - type: file
        path: com.cursor.cursor.png
      - type: file
        path: cursor
      - type: file
        path: npmrc
      - type: file
        path: flatpak-warning.txt
      - type: extra-data
        filename: cursor.AppImage
        only-arches: [x86_64]
        url: https://download.todesktop.com/230313mzl4w4u92/cursor-0.45.14-build-250219jnihavxsz-x86_64.AppImage
        sha256: e4c196262f133fed778d97fa60c314539b9863fdce053171b46a62aef823f192
        size: 154331840
        x-checker-data:
          type: electron-updater
          url: https://download.todesktop.com/230313mzl4w4u92/latest-linux.yml
          is-main-source: true
      - type: extra-data
        filename: cursor.AppImage
        only-arches: [aarch64]
        url: https://download.todesktop.com/230313mzl4w4u92/cursor-0.45.14-build-250219jnihavxsz-arm64.AppImage
        sha256: f0e5253ee3cd82a6c67b6c7b806fa6de7deee940ef82755e9248c9d3ca55391b
        size: 154439047
        x-checker-data:
          type: electron-updater
          url: https://download.todesktop.com/230313mzl4w4u92/latest-linux-arm64.yml

  - name: host-spawn
    buildsystem: simple
    build-commands:
      - install -Dm755 host-spawn ${FLATPAK_DEST}/bin/host-spawn
    sources:
      - type: file
        url: https://github.com/1player/host-spawn/releases/download/v1.6.1/host-spawn-x86_64
        sha256: 733746ab498e07d065cbecf80bacd447eb21846d1462e8fe23fdd9d9dc977b50
        dest-filename: host-spawn
        only-arches: [x86_64]
        x-checker-data:
          type: json
          url: https://api.github.com/repos/1player/host-spawn/releases/latest
          tag-query: .tag_name
          version-query: .tag_name
          timestamp-query: .published_at
          url-query: '[.assets[] | select(.name|test(".+x86_64$"))][0] | .browser_download_url'
      - type: file
        url: https://github.com/1player/host-spawn/releases/download/v1.6.1/host-spawn-aarch64
        sha256: 71b7744a4d0b29279523cc0f0ed1a7af5e9555510bd9e6d4685391b59faefaac
        dest-filename: host-spawn
        only-arches: [aarch64]
        x-checker-data:
          type: json
          url: https://api.github.com/repos/1player/host-spawn/releases/latest
          tag-query: .tag_name
          version-query: .tag_name
          timestamp-query: .published_at
          url-query: '[.assets[] | select(.name|test(".+aarch64$"))][0] | .browser_download_url'
