app-id: top.jtmonster.jhentai
runtime: org.gnome.Platform
runtime-version: '47'
sdk: org.gnome.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm19
command: jhentai
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --share=network
  - --device=dri
  - --talk-name=org.freedesktop.ScreenSaver
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc
modules:
  - name: jhentai
    buildsystem: simple
    build-options:
      build-args:
        - --share=network
      arch:
        x86_64:
          env:
            BUNDLE_PATH: build/linux/x64/release/bundle
        aarch64:
          env:
            BUNDLE_PATH: build/linux/arm64/release/bundle
      append-path: /usr/lib/sdk/llvm19/bin:/run/build/jhentai/flutter/bin
      prepend-ld-library-path: /usr/lib/sdk/llvm19/lib
      env:
        PUB_CACHE: /run/build/jhentai/.pub-cache
    build-commands:
      - flutter build linux --release --verbose --target lib/src/main.dart
      - mkdir -p ${FLATPAK_DEST}/bin
      - cp -r ${BUNDLE_PATH}/* ${FLATPAK_DEST}/bin
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
      - install -Dm644 linux/assets/${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications
      - install -Dm644 assets/icon/JHenTai_512.png ${FLATPAK_DEST}/share/icons/hicolor/512x512/apps/${FLATPAK_ID}.png
    sources:
      - type: git
        url: https://github.com/jiangtian616/JHenTai.git
        tag: v8.0.6+277
        commit: 8bc13ab2b678907e2bafd0724bde4ac6c342f8a2
        x-checker-data:
          type: git
          tag-pattern: ^v([\d.]+(?:\+\d+)?)$
      - type: file
        path: top.jtmonster.jhentai.metainfo.xml
      - type: git
        url: https://github.com/flutter/flutter.git
        tag: 3.24.5
        dest: flutter
