app-id: io.github.c0re100.qbittorrent-enhanced-edition
runtime: org.kde.Platform
sdk: org.kde.Sdk
runtime-version: '6.9'
command: qbittorrent
rename-icon: qbittorrent
rename-desktop-file: org.qbittorrent.qBittorrent.desktop
rename-appdata-file: org.qbittorrent.qBittorrent.metainfo.xml
copy-icon: true
finish-args:
  - --device=dri
  - --filesystem=host
  - --share=network
  - --socket=wayland
  - --system-talk-name=org.freedesktop.login1
  - --system-talk-name=org.freedesktop.UPower
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.freedesktop.ScreenSaver
  - --talk-name=org.freedesktop.PowerManagement
  - --talk-name=org.gnome.SessionManager
  - --talk-name=org.ayatana.indicator.application
  - --talk-name=org.kde.StatusNotifierWatcher
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc

modules:
  - name: boost
    buildsystem: simple
    build-commands:
      - ./bootstrap.sh --prefix=${FLATPAK_DEST}/ --with-libraries=headers
      - ./b2 install variant=release link=shared runtime-link=shared cxxflags="${CXXFLAGS}"
        linkflags="${LDFLAGS}" -j ${FLATPAK_BUILDER_N_JOBS}
    sources:
      - type: git
        url: https://github.com/boostorg/boost.git
        tag: boost-1.91.0
        commit: 1a80576db6b70828803819fb6925132193bc5d0e
        x-checker-data:
          type: git
          tag-pattern: ^boost-([\d.]+)$

  - name: libtorrent
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
    sources:
      - type: git
        url: https://github.com/arvidn/libtorrent.git
        tag: v2.0.13
        commit: 7d7fc38fac61177fa5e02148f791b2f65250b09d
        x-checker-data:
          type: git
          tag-pattern: ^v([\d.]+)$

  - name: qbittorrent
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
    sources:
      - type: git
        url: https://github.com/c0re100/qBittorrent-Enhanced-Edition.git
        tag: release-5.2.1.10
        commit: 18cfcc6958d0f5170c29edb68908c2c8365ec749
        x-checker-data:
          type: git
          tag-pattern: ^release-([\d.]+)$
