app-id: life.pugai.honzuki
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
command: Honzuki
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --share=network
  - --device=dri
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc
modules:
  - name: Honzuki
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - bsdtar --to-stdout -xf Honzuki.deb data.tar.zst | bsdtar -xf -
      - cp -r opt/Honzuki ${FLATPAK_DEST}/
      - cp -r usr/share ${FLATPAK_DEST}/
      - install -Dm755 Honzuki.sh ${FLATPAK_DEST}/bin/Honzuki
    sources:
      - type: file
        url: https://github.com/pugaizai/honzuki/releases/download/1.0.2/Honzuki-1.0.2-linux-amd64.deb
        only-arches: [x86_64]
        sha256: bdd032ecb1edacea8cf0bcdab192335eb4d9e00f17b129cb82b4d5e7af2e1160
        dest-filename: Honzuki.deb
        x-checker-data:
          type: json
          url: https://api.github.com/repos/pugaizai/Honzuki/releases/latest
          version-query: .tag_name
          url-query: >-
            .assets[] | select(.name=="Honzuki-" + $version + "-linux-amd64.deb")
            |
            .browser_download_url

      - type: script
        commands:
          - export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"
          - /app/Honzuki/Honzuki "$@"
        dest-filename: Honzuki.sh
