app-id: com.hoppscotch.hoppscotch
runtime: org.gnome.Platform
runtime-version: '47'
sdk: org.gnome.Sdk
command: hoppscotch
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --share=network
  - --device=dri
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc
modules:
  - name: hoppscotch
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
      - install -Dm755 usr/bin/hoppscotch /app/bin/hoppscotch
      - install -Dm644 usr/share/applications/hoppscotch.desktop /app/share/applications/com.hoppscotch.hoppscotch.desktop
      - install -Dm644 com.hoppscotch.hoppscotch.metainfo.xml /app/share/metainfo/com.hoppscotch.hoppscotch.metainfo.xml
      - for size in {32x32,48x48,64x64,128x128,256x256@2}; do install -Dm644 usr/share/icons/hicolor/$size/apps/hoppscotch.png
        /app/share/icons/hicolor/$size/apps/com.hoppscotch.hoppscotch.png; done
      - desktop-file-edit --set-key="Categories" --set-value="Development;Network;"
        --set-key="Icon" --set-value="com.hoppscotch.hoppscotch" /app/share/applications/com.hoppscotch.hoppscotch.desktop
    sources:
      - type: file
        only-arches: [x86_64]
        url: https://github.com/hoppscotch/releases/releases/download/v24.10.2-0/Hoppscotch_linux_x64.deb
        sha256: e8b3f3f7bcbc49996571f67e84a667d556485a139b85c3f91a75b96d66a11838
        x-checker-data:
          type: json
          url: https://api.github.com/repos/hoppscotch/releases/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: >-
            .assets[] | select(.name | test("Hoppscotch_linux_x64.deb"))
            |
            .browser_download_url
      - type: file
        path: com.hoppscotch.hoppscotch.metainfo.xml
