app-id: com.hoppscotch.hoppscotch
runtime: org.gnome.Platform
runtime-version: '47'
sdk: org.gnome.Sdk
command: hoppscotch
rename-icon: hoppscotch
rename-desktop-file: hoppscotch.desktop
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --share=network
  - --device=dri
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc
modules:
  - name: hoppscotch
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
      - desktop-file-edit --set-key="Categories" --set-value="Development;Network;"
        usr/share/applications/hoppscotch.desktop
      - install -Dm755 usr/bin/hoppscotch ${FLATPAK_DEST}/bin/hoppscotch
      - install -Dm644 usr/share/applications/hoppscotch.desktop -t ${FLATPAK_DEST}/share/applications
      - install -Dm644 usr/share/icons/hicolor/128x128/apps/hoppscotch.png -t ${FLATPAK_DEST}/share/icons/hicolor/128x128/apps
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
    sources:
      - type: file
        only-arches: [x86_64]
        url: https://github.com/hoppscotch/releases/releases/download/v24.12.2-0/Hoppscotch_linux_x64.deb
        sha256: a83a26dd2fcbde15ba8844a4970d8274c2c71a488d2c91364f3c88accb1fc89a
        x-checker-data:
          type: json
          url: https://api.github.com/repos/hoppscotch/releases/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: >-
            .assets[] | select(.name | test("Hoppscotch_linux_x64.deb"))
            |
            .browser_download_url
      - type: file
        path: com.hoppscotch.hoppscotch.metainfo.xml
