id: org.freedesktop.Platform.electron34
branch: '24.08'
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
build-extension: true
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc
modules:
  - name: electron
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - unzip electron.zip -d ${FLATPAK_DEST}
    sources:
      - type: file
        dest-filename: electron.zip
        only-arches: [aarch64]
        url: https://github.com/electron/electron/releases/download/v34.5.8/electron-v34.5.8-linux-arm64.zip
        sha256: 2172a9fa02331ba9c645dd6a6c5c6c07235e902c0aebb61b123d2f6c3ea0121f
      - type: file
        dest-filename: electron.zip
        only-arches: [x86_64]
        url: https://github.com/electron/electron/releases/download/v34.5.8/electron-v34.5.8-linux-x64.zip
        sha256: da78b040068b6f0d41b3ccc5e5d26f1130bcdeba83f23ebbdae416c26bcf80e2
