app-id: io.github.slotsun.simplelive
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm20
command: simple_live_app
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --socket=pulseaudio
  - --share=network
  - --device=dri
  - --talk-name=org.freedesktop.ScreenSaver
  - --system-talk-name=org.freedesktop.NetworkManager
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc

modules:
  # - mpv/mpv.yaml
  - name: simplelive
    buildsystem: simple
    build-commands:
      - bsdtar --to-stdout -xvf simplelive.deb data.* | bsdtar -xvf -
      - cp -rv usr/share/simple_live_app ${FLATPAK_DEST}/simplelive
      - install -Dvm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
      - install -Dvm644 ${FLATPAK_ID}.png -t ${FLATPAK_DEST}/share/icons/hicolor/512x512/apps
      - install -Dvm644 usr/share/applications/simple_live_app.desktop -t ${FLATPAK_DEST}/share/applications
    sources:
      - type: file
        dest-filename: simplelive.deb
        url: 
        sha256: 
        x-checker-data:
          type: json
          url: https://api.github.com/repos/SlotSun/dart_simple_live/releases/latest
          tag-query: .tag_name
          version-query: .tag_name | sub("^v"; "")
          timestamp-query: .published_at
          url-query: >-
            .assets[] | select(.name | contains(".deb")) |
            .browser_download_url
          is-main-source: true
      - type: file
        path: io.github.slotsun.simplelive.metainfo.xml
      - type: file
        path: io.github.slotsun.simplelive.desktop
      - type: file
        url: https://raw.githubusercontent.com/SlotSun/dart_simple_live/refs/heads/master/assets/logo.png
        dest-filename: io.github.slotsun.simplelive.png
        sha256: 1cfc6912cf1a977b3e21155e8cdc4ebdd10eb9d7a46b62064c7ad5e8c1876b8f
