app-id: xyz.chatboxapp.ce
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: '24.08'
separate-locales: false
command: chatbox

finish-args:
  - --share=ipc
  - --socket=x11
  - --device=dri
  - --share=network
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.kde.StatusNotifierWatcher
  # required to fix cursor scaling on wayland
  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc

modules:
  - name: chatboxapp
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - install -Dm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications
      - install -Dm644 ${FLATPAK_ID}.png -t ${FLATPAK_DEST}/share/icons/hicolor/512x512/apps/
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
      - install -Dm755 chatbox -t ${FLATPAK_DEST}/bin/
      - install -Dm755 apply_extra -t ${FLATPAK_DEST}/bin/
    sources:
      - type: extra-data
        only-arches: [aarch64]
        url: https://github.com/Bin-Huang/chatbox/releases/download/v0.10.4/Chatbox.CE-0.10.4-arm64.deb
        sha256: b283bbdc42fdc82d90592df3c78a95b4addd4bde577c64d882c040eb48431314
        filename: chatboxapp.deb
        size: 67387142
        x-checker-data:
          type: json
          url: https://api.github.com/repos/Bin-Huang/chatbox/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: >-
            .assets[] | select(.name | test("Chatbox.CE-" + $version + "-arm64.deb"))
            |
            .browser_download_url
      - type: extra-data
        only-arches: [x86_64]
        url: https://github.com/Bin-Huang/chatbox/releases/download/v0.10.4/Chatbox.CE-0.10.4-amd64.deb
        sha256: 532d0b8664a68c9f3ec44af2c4e475905c58c3736d95ef195c5b812d0a26ab22
        filename: chatboxapp.deb
        size: 71342892
        x-checker-data:
          type: json
          url: https://api.github.com/repos/Bin-Huang/chatbox/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: >-
            .assets[] | select(.name | test("Chatbox.CE-" + $version + "-amd64.deb"))
            |
            .browser_download_url
      - type: file
        path: xyz.chatboxapp.ce.metainfo.xml
      - type: file
        path: xyz.chatboxapp.ce.png
      - type: file
        path: xyz.chatboxapp.ce.desktop
      - type: script
        dest-filename: chatbox
        commands:
          - export TMPDIR=${XDG_RUNTIME_DIR}/app/${FLATPAK_ID}
          - WAYLAND_SOCKET=${WAYLAND_DISPLAY:-"wayland-0"}
          - |
            if [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_SOCKET}" || -e "${WAYLAND_DISPLAY}" ]]
            then
                FLAGS="--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime"
            fi
          - exec zypak-wrapper "/app/extra/chatbox/xyz.chatboxapp.ce" $FLAGS "$@"
      - type: script
        dest-filename: apply_extra
        commands:
          - bsdtar --to-stdout -xf chatboxapp.deb data.tar.xz | bsdtar -xf -
          - mv "opt/Chatbox CE" ./chatbox
          - rm -r chatboxapp.deb usr opt
