id: org.freedesktop.Platform.electron
branch: '24.08'
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
build-extension: true
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc
modules:
  - name: electron
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - unzip electron.zip -d ${FLATPAK_DEST}
    sources:
      - type: file
        dest-filename: electron.zip
        only-arches: [aarch64]
        url: https://github.com/electron/electron/releases/download/v35.1.4/electron-v35.1.4-linux-arm64.zip
        sha256: 10485b16520abdf6d4d782bafee996eb189f605f0632727a726f4c2ef73fdb6d
        x-checker-data:
          type: anitya
          project-id: 17779
          stable-only: true
          url-template: https://github.com/electron/electron/releases/download/v$version/electron-v$version-linux-arm64.zip
      - type: file
        dest-filename: electron.zip
        only-arches: [x86_64]
        url: https://github.com/electron/electron/releases/download/v35.1.4/electron-v35.1.4-linux-x64.zip
        sha256: 19a6b1a90bb9c13ad5ba1dcb8ebe1b98d9f8b8488e7731e56199c2a4971d7b47
        x-checker-data:
          type: anitya
          project-id: 17779
          stable-only: true
          url-template: https://github.com/electron/electron/releases/download/v$version/electron-v$version-linux-x64.zip
