id: org.freedesktop.Platform.electron
branch: '26.08'
runtime: org.freedesktop.Platform
runtime-version: '26.08'
sdk: org.freedesktop.Sdk
build-extension: true
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc
modules:
  - name: electron
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - unzip electron.zip -d ${FLATPAK_DEST}
    sources:
      - type: file
        dest-filename: electron.zip
        only-arches: [aarch64]
        url: https://github.com/electron/electron/releases/download/v44.4.4/electron-v44.4.4-linux-arm64.zip
        sha256: b7e7e0035d1cf7cd0c3a5e132d3cf261b3049cd3286b89b29b9b7e64b72b4635
        x-checker-data:
          type: anitya
          project-id: 17779
          stable-only: true
          url-template: https://github.com/electron/electron/releases/download/v$version/electron-v$version-linux-arm64.zip
      - type: file
        dest-filename: electron.zip
        only-arches: [x86_64]
        url: https://github.com/electron/electron/releases/download/v44.4.4/electron-v44.4.4-linux-x64.zip
        sha256: 371dfb6eb7f300f83932d010984f3419af162146b1c20631a8c89938d4338f3e
        x-checker-data:
          type: anitya
          project-id: 17779
          stable-only: true
          url-template: https://github.com/electron/electron/releases/download/v$version/electron-v$version-linux-x64.zip
