id: org.freedesktop.Platform.electron
branch: '25.08'
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
build-extension: true
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc
modules:
  - name: electron
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - unzip electron.zip -d ${FLATPAK_DEST}
    sources:
      - type: file
        dest-filename: electron.zip
        only-arches: [aarch64]
        url: https://github.com/electron/electron/releases/download/v43.3.0/electron-v43.3.0-linux-arm64.zip
        sha256: 3e89a62c345d8171bf54f77df5b3d8216c492847eed00ae59cadd78d6f5535f7
        x-checker-data:
          type: anitya
          project-id: 17779
          stable-only: true
          url-template: https://github.com/electron/electron/releases/download/v$version/electron-v$version-linux-arm64.zip
      - type: file
        dest-filename: electron.zip
        only-arches: [x86_64]
        url: https://github.com/electron/electron/releases/download/v43.3.0/electron-v43.3.0-linux-x64.zip
        sha256: f4987e9f045e46b117f0805d6ba4dc524e2abb2c2e33660f175bb39564bd3dae
        x-checker-data:
          type: anitya
          project-id: 17779
          stable-only: true
          url-template: https://github.com/electron/electron/releases/download/v$version/electron-v$version-linux-x64.zip
