id: org.freedesktop.Platform.electron
branch: '26.08'
runtime: org.freedesktop.Platform
runtime-version: '26.08'
sdk: org.freedesktop.Sdk
build-extension: true
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc
modules:
  - name: electron
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - unzip electron.zip -d ${FLATPAK_DEST}
    sources:
      - type: file
        dest-filename: electron.zip
        only-arches: [aarch64]
        url: https://github.com/electron/electron/releases/download/v44.4.3/electron-v44.4.3-linux-arm64.zip
        sha256: 61f084a5ac0f1835efc12b9db17042d92c8c617b03578f96a888acd4a05a0b10
        x-checker-data:
          type: anitya
          project-id: 17779
          stable-only: true
          url-template: https://github.com/electron/electron/releases/download/v$version/electron-v$version-linux-arm64.zip
      - type: file
        dest-filename: electron.zip
        only-arches: [x86_64]
        url: https://github.com/electron/electron/releases/download/v44.4.3/electron-v44.4.3-linux-x64.zip
        sha256: fe880a7e37160cfd4e00193bc4c713ead7a778abfe74860a2d36d86fd0be48a8
        x-checker-data:
          type: anitya
          project-id: 17779
          stable-only: true
          url-template: https://github.com/electron/electron/releases/download/v$version/electron-v$version-linux-x64.zip
