id: org.freedesktop.Platform.electron
branch: '24.08'
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
build-extension: true
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc
modules:
  - name: electron
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - unzip electron.zip -d ${FLATPAK_DEST}
    sources:
      - type: file
        dest-filename: electron.zip
        only-arches: [aarch64]
        url: https://github.com/electron/electron/releases/download/v34.3.0/electron-v34.3.0-linux-arm64.zip
        sha256: 06895af4db0762a2c33f065bd71b92ebec5c9c557ffb2e3402aac74880687310
        x-checker-data:
          type: anitya
          project-id: 17779
          stable-only: true
          url-template: https://github.com/electron/electron/releases/download/v$version/electron-v$version-linux-arm64.zip
      - type: file
        dest-filename: electron.zip
        only-arches: [x86_64]
        url: https://github.com/electron/electron/releases/download/v34.3.0/electron-v34.3.0-linux-x64.zip
        sha256: 263ce56f37b6ab7954d1644bebd429c4c1522ddc48b55e8b3cbc4098def62588
        x-checker-data:
          type: anitya
          project-id: 17779
          stable-only: true
          url-template: https://github.com/electron/electron/releases/download/v$version/electron-v$version-linux-x64.zip
