app-id: co.anysphere.cursor
runtime: org.freedesktop.Sdk
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.golang
base: org.electronjs.Electron2.BaseApp
base-version: '24.08'
rename-icon: cursor
command: cursor
finish-args:
  - --share=network
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  - --socket=ssh-auth
  - --device=all
  - --allow=devel
  - --filesystem=host
  - --env=NPM_CONFIG_GLOBALCONFIG=/app/etc/npmrc
  - --env=LD_LIBRARY_PATH=/app/lib
  # required to fix cursor scaling on wayland
  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
  - --system-talk-name=org.freedesktop.login1
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.freedesktop.secrets
  - --talk-name=org.kde.kwalletd5
  - --talk-name=org.freedesktop.Flatpak
  - --filesystem=xdg-run/gnupg:ro
  - --filesystem=xdg-config/kdeglobals:ro
  - --talk-name=com.canonical.AppMenu.Registrar

add-extensions:
  com.visualstudio.code.tool:
    directory: tools
    subdirectories: true
    versions: stable;24.08
    add-ld-path: lib
    no-autodownload: true

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc

modules:
  - shared-modules/libusb/libusb.json

  # Provide libsecret without gcrypt, forcing it to use the D-Bus backend
  # https://github.com/flathub/org.signal.Signal/pull/756/commits/2caf105b18f906e7707f67b3cf7384a21f461564
  - name: libsecret
    buildsystem: meson
    config-opts:
      - -Dmanpage=false
      - -Dcrypto=disabled
      - -Dvapi=false
      - -Dgtk_doc=false
      - -Dintrospection=false
      - -Dbash_completion=disabled
    cleanup:
      - /bin
      - /include
      - /lib/pkgconfig
      - /share/man
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/libsecret.git
        tag: 0.21.7
        commit: 0936f740c02b60f02657729cd99f581db4517a41
        x-checker-data:
          type: git
          tag-pattern: ^([\d.]+)$

  - name: krb5
    buildsystem: simple
    post-install:
      - install -Dm644 ../krb5.conf /app/etc/krb5.conf
    build-commands:
      - autoreconf -i
      - ./configure --prefix=${FLATPAK_DEST}
      - make -j ${FLATPAK_BUILDER_N_JOBS}
      - make install
    subdir: src
    sources:
      - type: git
        url: https://github.com/krb5/krb5.git
        tag: krb5-1.21.3-final
        commit: 8f56f544dd179056e9b8d02552e6c5e392eb2966
        x-checker-data:
          type: git
          tag-pattern: ^krb5-([\d.]+)-final$
      - type: file
        path: krb5.conf

  - name: host-spawn
    buildsystem: simple
    build-options:
      build-args:
        - --share=network
      append-path: /usr/lib/sdk/golang/bin
    build-commands:
      - CGO_ENABLED=0 go build -ldflags "-X main.Version=$(grep -m1 -oP '^\s*##\s*\K\d+\.\d+\.\d+'
        CHANGELOG.md)" -o "${FLATPAK_DEST}/bin/host-spawn"
    sources:
      - type: git
        url: https://github.com/1player/host-spawn
        tag: v1.6.1
        commit: db1173ae2ef04beca8961a35c225117498263e23
        x-checker-data:
          type: git
          tag-pattern: ^v([\d.]+)$

  - name: unappimage
    buildsystem: simple
    build-commands:
      - make -C squashfs-tools install INSTALL_DIR=${FLATPAK_DEST}/bin
    sources:
      - type: git
        url: https://github.com/refi64/unappimage
        commit: d7f86f2a0d7ec3a69211125207d5f127386b849a

  - name: cursor
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - mv icons ${FLATPAK_DEST}/share/icons/
      - install -Dm755 cursor -t ${FLATPAK_DEST}/bin/
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo/
      - install -Dm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications/
      - install -Dm644 ${FLATPAK_ID}-url-handler.desktop -t /app/share/applications/
      - install -Dm644 ${FLATPAK_ID}-workspace.xml -t /app/share/mime/packages/
      - install -Dm644 npmrc -t ${FLATPAK_DEST}/etc/
      - install -Dm644 flatpak-warning.txt -t ${FLATPAK_DEST}/share/cursor
      - install -Dm755 apply_extra -t ${FLATPAK_DEST}/bin/
      - mkdir ${FLATPAK_DEST}/tools
    sources:
      - type: script
        dest-filename: apply_extra
        commands:
          - chmod +x cursor.AppImage
          - unappimage cursor.AppImage >/dev/null
          - mv squashfs-root/usr/share/cursor .
          - rm -rf squashfs-root
      - type: file
        path: co.anysphere.cursor.metainfo.xml
      - type: file
        path: co.anysphere.cursor.desktop
      - type: file
        path: co.anysphere.cursor-url-handler.desktop
      - type: file
        path: co.anysphere.cursor-workspace.xml
      - type: dir
        path: cursor-icons
      - type: file
        path: cursor
      - type: file
        path: npmrc
      - type: file
        path: flatpak-warning.txt
      - type: extra-data
        filename: cursor.AppImage
        only-arches: [x86_64]
        url: https://downloads.cursor.com/production/224bc1da1a36703c583d62e407d4bccbb8c6a641/linux/x64/Cursor-0.49.3-x86_64.AppImage
        sha256: b5ada6d53155b5befdd870cddd596d61ddda61e3c2e7166d52cdeecc978d0a6f
        size: 187053248
      - type: extra-data
        filename: cursor.AppImage
        only-arches: [aarch64]
        url: https://downloads.cursor.com/production/224bc1da1a36703c583d62e407d4bccbb8c6a641/linux/arm64/Cursor-0.49.3-aarch64.AppImage
        sha256: 71a28a07f3ea7ce7729adf9520681830c83f900798c75cbb3e8624ea32a27393
        size: 171469320
